Repository ss3-wizard/SS3_web, pull requests merged in 2019-02, with the labels that each got.

#5 song_chatting
  README_SONG.MD
  README_SONG.md
Labels: help wanted

#7 Feature/calculator
  README.md
  SS3_web/settings.py
  SS3_web/urls.py
  calculator/__init__.py
  calculator/admin.py
  calculator/apps.py
  calculator/migrations/__init__.py
  calculator/models.py
  calculator/templates/calculator/index.html
  calculator/tests.py
  calculator/urls.py
  calculator/views.py
  home/static/home/js/calculator.js
Labels: add-feature

#9 Feature/login
  SS3_web/settings.py
  SS3_web/urls.py
  account/__init__.py
  account/admin.py
  account/apps.py
  account/forms.py
  account/migrations/__init__.py
  account/models.py
  account/static/account/css/account.css
  account/static/account/images/google-btn.png
  account/templates/account/index.html
  account/templates/account/sign_in.html
  account/templates/account/sign_up.html
  account/tests.py
  account/urls.py
  account/views.py
  requirements.txt
Labels: add-feature

#10 Feature/base layout
  home/static/home/css/_footer.css
  home/static/home/css/_nav.css
  home/static/home/css/base.css
  home/static/home/images/go_to_top.png
  home/static/home/images/header.jpg
  home/static/home/js/_footer.js
  home/static/home/js/_nav.js
  home/static/home/js/base.js
  home/templates/home/_footer.html
  home/templates/home/_nav.html
  home/templates/home/base.html
Labels: add-feature, enhancement
